# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoliviaV_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoliviaV_ios

	pod 'FirebaseAuth'
	pod 'FirebaseMessaging'
	pod 'FirebaseDatabase'

  target 'BoliviaV_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoliviaV_iosUITests' do
    # Pods for testing
  end

end
